name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: pre-commit-hooks
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: rm -rf /opt&
    - run: nix-build --keep-going --impure
      env:
        NIXPKGS_ALLOW_UNFREE: 1
  tests-flakes:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: pre-commit-hooks
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: rm -rf /opt&
    - run: nix flake check -L --show-trace --impure
      env:
        NIXPKGS_ALLOW_UNFREE: 1
    - run: nix eval .#lib.x86_64-linux.run --show-trace
